[workspace]

members = [
    "apps/cloud",
    "apps/keck",
    "libs/cang-jie",
    "libs/jwst",
    "libs/octo-text-search",
    # "libs/jwst-ffi",
    # "libs/jwst-jni",
    "libs/jwst-logger",
    # "libs/jwst-py",
    "libs/jwst-storage",
    # "libs/jwst-wasm",
]

exclude = ["forks/y-crdt/yrs", "forks/y-crdt/lib0", "forks/y-sync"]

[patch.crates-io]
yrs = { path = 'forks/y-crdt/yrs' }
lib0 = { path = 'forks/y-crdt/lib0' }
y-sync = { path = 'forks/y-sync' }

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
