[workspace]

members = [
    "apps/cloud",
    "apps/keck",
    "libs/cloud-database",
    "libs/cloud-database/migration",
    "libs/jwst",
    "libs/jwst-binding/jwst-ffi",
    "libs/jwst-binding/jwst-jni",
    # "libs/jwst-binding/jwst-py",
    "libs/jwst-binding/jwst-swift",
    # "libs/jwst-binding/jwst-wasm",
    "libs/jwst-logger",
    "libs/jwst-static",
    "libs/jwst-storage",
    "libs/jwst-storage/src/blobs/migration",
    "libs/jwst-storage/src/docs/migration",
    "libs/OctoBase",
    "libs/vendors/cang-jie",
    "libs/vendors/y-sync",
    "libs/vendors/y-crdt-0.14/yrs",
    "libs/vendors/y-crdt-0.14/lib0",
]

exclude = ["libs/vendors/y-crdt/yrs"]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1

[patch.crates-io]
rust-embed = { git = "https://github.com/pyrossh/rust-embed", rev = "7c0fc42" }
yrs = { path = 'libs/vendors/y-crdt/yrs' }
y-sync = { path = 'libs/vendors/y-sync' }
