[package]
name = "keck"
version = "0.1.0"
authors = ["DarkSky <darksky2048@gmail.com>"]
edition = "2021"
license = "AGPL-3.0-only"

[features]
default = ["jwst"]
affine = ["jwst-storage/sqlite"]
jwst = ["api", "schema", "docs", "jwst-storage/sqlite"]
mysc = ["api", "schema", "docs", "jwst-storage/mysql"]
api = ["utoipa"]
docs = ["mdbook"]
schema = ["utoipa-swagger-ui"]

[dependencies]
anyhow = "^1.0.68"
axum = { version = "0.6.4", features = ["headers", "ws"] }
cfg-if = "^1.0.0"
dashmap = "^5.4.0"
futures = "^0.3.25"
http = "^0.2.8"
lib0 = { version = "0.12.2", features = ["lib0-serde"] }
log = { version = "^0.4.17", features = [
  "max_level_trace",
  "release_max_level_info",
] }
serde = { version = "^1.0.151", features = ["derive"] }
serde_json = "^1.0.91"
sqlx = { version = "^0.6.2", features = [
  "chrono",
  "macros",
  "migrate",
  "runtime-tokio-rustls",
] }
tower = "^0.4.13"
tower-http = { version = "^0.3.5", features = ["cors"] }
thiserror = "^1.0.38"
time = "^0.3.17"
tokio = { version = "^1.23.0", features = [
  "macros",
  "rt-multi-thread",
  "signal",
] }
utoipa = { version = "^2.4.2", features = ["axum_extras"], optional = true }
utoipa-swagger-ui = { version = "^2.0.2", features = ["axum"], optional = true }
uuid = { version = "^1.2.2", default-features = false, features = ["v4"] }

# ======= workspace dependencies =======

jwst = { path = "../../libs/jwst" }
jwst-logger = { path = "../../libs/jwst-logger" }
jwst-static = { path = "../../libs/jwst-static" }
jwst-storage = { path = "../../libs/jwst-storage" }
yrs = "=0.12.0"

[dev-dependencies]
axum-test-helper = "0.2.0"

[build-dependencies]
mdbook = { version = "^0.4.25", default-features = false, optional = true }

[profile.dev.package.sqlx-macros]
opt-level = 3
